### ISSUE TITLE
update svg files to match Vertex-Maia colour-wise

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/vertex-maia-icon-themes#1]
We have to update the colour-shemes to match Vertex-Maia

**Comment by philmmanjaro** [comment]
**#27ae60** needs to be changed with the matching colour.

**Comment by oberon2007** [comment]
Yes, sounds like a good plan! :smile: Maia green is **#16a085**
I don't have an overview of Menda icons yet. We'd basically just have to single out the ncessary ones and then see what mogrify values are needed. I can offer to do that bit.
How many icons are we talking about?

**Comment by philmmanjaro** [comment]
30+ or so. Most the folder icons in:
https://github.com/manjaro/vertex-maia-icon-themes/tree/master/Vertex-Maia-Circle/places/scalable
https://github.com/manjaro/vertex-maia-icon-themes/tree/master/Vertex-Maia-Circle/places/small

**Comment by oberon2007** [comment]
I'll give it a try tonight. If they're all in the same place more or less or have similar unique names we can simply run mogrify on them once we have the right values...

**Comment by oberon2007** [comment]
So, we're basically trying to produce **menda-maia-icons** chrchrchr, brilliant! :laughing:

**Comment by philmmanjaro** [comment]
Some like that. We had worked on the icons for so long, so we can't drop them. What the name is, doesn't matter in the end. I'll use them for the XFCE edition. Others can then choose which of the matching icon sets they want use then. Open choice :smiley:

**Comment by oberon2007** [comment]
I'm highly motivated... The reason is that none of the existing sets now works properly for Cinnamon or i3... :stuck_out_tongue_closed_eyes:

**Comment by oberon2007** [comment]
Not only the name is funny. Fact is that we are now trying to produce icons to match a gtk-theme that we developed to match icons, haha! :yum:

**Comment by oberon2007** [comment]
this repo can be removed :stuck_out_tongue_winking_eye: 
Happy Birthday Phil! :smiley:
