### ISSUE TITLE
color adjustment

### ISSUE THREAD

**Issue by oberon2007** [manjaro/vertex-maia-icon-themes#2]
Actually I realize that we still need to adjust the folder color of vertex-icons a little. Since they are flat with no border their shape disappears in the identical highlight color :wink: 
![maia_icon](https://cloud.githubusercontent.com/assets/11800714/15589485/630de5d8-2393-11e6-9e99-4afa70c574a1.png)

So should we have them just a little brighter?
![maia_brighter](https://cloud.githubusercontent.com/assets/11800714/15589503/78dd0ff6-2393-11e6-929a-bd7a09599e75.png)

or even brighter?
![maia_evenbrighter](https://cloud.githubusercontent.com/assets/11800714/15589525/92c19d10-2393-11e6-9728-2fad88585784.png)

When they get too bright, the contrast with **vertex-maia-dark** theme maybe gets a little bit too hard?
![maia_brightestwithdark](https://cloud.githubusercontent.com/assets/11800714/15589558/bd69a440-2393-11e6-9ff5-7604f64cad8b.png)

Of course they could also be darker:
![maia_dark](https://cloud.githubusercontent.com/assets/11800714/15589566/cf0be28a-2393-11e6-8e66-bbc413d32df0.png)
![maia_darkwithdark](https://cloud.githubusercontent.com/assets/11800714/15589567/cf101eb8-2393-11e6-9161-b747aedf08df.png)

What would be your preference, @philmmanjaro ?

**Comment by oberon2007** [comment]
I think the just-a-little-brighter version will be good. Also because the difference to what is now already established is almost not perceptible.

**Comment by oberon2007** [comment]
That would be **#18b193**.

**Comment by philmmanjaro** [comment]
Ok, then go for it.
